version: '2.4'

services:
  publisher:
    build:
      context: .
      args:
        EXECUTABLE: publisher
    environment:
      NUMBER_OF_JOB_IDS: 1000
      NUMBER_OF_JOBS: 100000

  worker:
    build:
      context: .
      args:
        EXECUTABLE: worker
    scale: 6

  reporter:
    build:
      context: .
      args:
        EXECUTABLE: reporter
    environment:
      NUMBER_OF_JOBS: 100000
