version: '2.4'

services:
  publisher:
    build:
      context: .
      args:
        EXECUTABLE: publisher
    environment:
      NUMBER_OF_JOB_IDS: 10
      NUMBER_OF_JOBS: 100
      RABBITMQ_URL: amqp://test:test123@rabbitmq:5672/
    depends_on:
      rabbitmq:
        condition: service_healthy

  worker:
    build:
      context: .
      args:
        EXECUTABLE: worker
    environment:
      RABBITMQ_URL: amqp://test:test123@rabbitmq:5672/
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3.8.2-management
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: test123
    ports:
      - 127.0.0.1:5672:5672
      - 127.0.0.1:15672:15672
    healthcheck:
      test: rabbitmqctl status