version: '2.4'

services:
  generator:
    environment:
      MESSAGING_STRATEGY: ZeroMQ
      ZEROMQ_JOBS_ENDPOINT_PORT: 8888
    expose:
      - 8888

  worker:
    environment:
      MESSAGING_STRATEGY: ZeroMQ
      ZEROMQ_JOBS_ENDPOINT_NAME: generator
      ZEROMQ_JOBS_ENDPOINT_PORT: 8888
      ZEROMQ_RESULTS_ENDPOINT_NAME: reporter
      ZEROMQ_RESULTS_ENDPOINT_PORT: 7777
      ZEROMQ_TERMINATE_ENDPOINT_NAME: reporter
      ZEROMQ_TERMINATE_ENDPOINT_PORT: 9999
    scale: 6

  reporter:
    environment:
      MESSAGING_STRATEGY: ZeroMQ
      ZEROMQ_RESULTS_ENDPOINT_PORT: 7777
      ZEROMQ_TERMINATE_ENDPOINT_PORT: 9999
    expose:
      - 7777
      - 9999
