version: '3.1'

services:
  rabbitmq:
    image: rabbitmq:3.8.2-management
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: test123
    ports:
      - 127.0.0.1:5672:5672
      - 127.0.0.1:15672:15672
